version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=issue-tracker

    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    command: npm run start:db
    depends_on:
      - postgres
    env_file:
      - ./src/configs/.env
    ports:
      - 3000:3000

volumes:
  postgres_db:
    driver: local